apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aouraghm/test-app-repo.git
    path: helm-charts/test-app-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: v1.2.3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

