harborAdminPassword: Harbor12345
externalURL: http://localhost:30002

expose:
  type: nodePort
  tls:
    enabled: false
features:
  chartMuseum:
    enabled: false  # omdat je OCI gebruikt

database:
  internal:
    enabled: false
  external:
    host: harbor-db-postgresql.harbor-db.svc.cluster.local
    port: 5432
    username: harbor
    password: HarborDB123
    coreDatabase: registry
    sslmode: disable

