harborAdminPassword: Harbor12345
externalURL: http://localhost:30080

expose:
  type: nodePort
  tls:
    enabled: false

database:
  internal:
    enabled: false
  external:
    host: harbor-db-postgresql.harbor-db.svc.cluster.local
    port: 5432
    username: harbor
    password: HarborDB123
    coreDatabase: registry
    sslmode: disable

